// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCxOGiwHA3EYzjue2KEBvecLqWpk9CJo',
    appId: '1:213012066784:web:295a404ac9d92662e7bb85',
    messagingSenderId: '213012066784',
    projectId: 'ciihackathon-b046d',
    authDomain: 'ciihackathon-b046d.firebaseapp.com',
    storageBucket: 'ciihackathon-b046d.appspot.com',
    measurementId: 'G-2HHGCD60RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdScJLhLUy4727OlKsSME4pKelXE7uBg',
    appId: '1:213012066784:android:948363badb015e58e7bb85',
    messagingSenderId: '213012066784',
    projectId: 'ciihackathon-b046d',
    storageBucket: 'ciihackathon-b046d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtJks0jPUTYDYiC29-0_HV6Izs5hnhkQ',
    appId: '1:213012066784:ios:fcaf475ebc5c25c6e7bb85',
    messagingSenderId: '213012066784',
    projectId: 'ciihackathon-b046d',
    storageBucket: 'ciihackathon-b046d.appspot.com',
    iosClientId: '213012066784-dderq2mnj1kq34nsfd2nsepthv3vr91e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciihackathon',
  );
}
